Make the polling interval configurable.
zama-ai/fhevm-backend pull request #170
Opened 2024-12-04 10:55 UTC by manoranjith

[feat: make coprocessor sync interval configurable](https://github.com/zama-ai/fhevm-backend/commit/cebb72d51efbc326d0eb671599b6573baa145ddd) 

- Currently, this value is hardcoded to 10s. This could be too long,
  leading to artificial delay in the ciphertext being available in the
  coprocessor db.

- Now, make it configurable via environment variable.

[feat: make worker job polling interval config](https://github.com/zama-ai/fhevm-backend/commit/669189c2f02ce3994aafbbd33c5c950d753cf1e6) 

- Previously, the value was hardcoded to 5000ms. This could lead to long
  wait between processing jobs and hence a delay in result being
  available in the coprocessor db.

- Now, make this interval configurable via command line argument. Can be
  fine tuned as per needed performance.

[chore: bump version to v0.1.2](https://github.com/zama-ai/fhevm-backend/commit/7ff32f34cfb59a2e2aeacd52cc5a4fc7ac7a5802)

2024-12-04 18:04 UTC, fd0r commented on fhevm-engine/coprocessor/src/daemon_cli.rs
> +    #[arg(long, default_value_t = 5000)]
Shouldn't we set it to a second by default @manoranjith ?

2024-12-04 18:04 UTC, fd0r approved these changes

2024-12-04 22:20 UTC, fd0r commented
Don't forget to follow conventional commit when adding this new config 😉 (aka breaking change)

https://www.conventionalcommits.org/en/v1.0.0/

2024-12-05 12:42 UTC, immortal-tofu requested changes

2024-12-05 13:36 UTC, manoranjith commented on fhevm-engine/coprocessor/Cargo.toml
> +version = "0.1.2"
Has the convention changed ?

In the [fhevm-devops](https://github.com/zama-ai/fhevm-devops/blob/0937486211d0dd5bb6addaf1e6d444a14aae2f5c/coprocessor/docker-compose/docker-compose-coprocesor.yml#L14) and [kms-core-infra](https://github.com/zama-ai/kms-core-infra/blob/82f0068b080d76cb59702e5cc44c4a5435fb62b3/kubernetes/gitops/environments/testnet-v1/coprocessor-sepolia-v1/coprocessor.yaml#L36), i see the `v0.1.1` convention being used.

2024-12-05 13:38 UTC, manoranjith commented on fhevm-engine/coprocessor/src/daemon_cli.rs
> +    #[arg(long, default_value_t = 5000)]
Yes, i could.

I just set the default to previously hard-coded value, since we can anyways override this config.

2024-12-05 13:56 UTC, manoranjith commented
The link is fixed.

2024-12-05 14:00 UTC, manoranjith commented
@fd0r Thanks for highlighting this could be a breaking change. 

I guess, i can make this a more soft change by adding a default value for `FHEVM_COPROCESSOR_SYNC` interval as well, when it is not set.

The other config already has a default.

2024-12-05 14:22 UTC, immortal-tofu commented on fhevm-engine/coprocessor/Cargo.toml
> +version = "0.1.2"
fhEVM is in 0.6.0. We want to keep in sync between the library/contracts/backend to avoid confusion. Probably in the future we'll derive: the backend will evolve while contracts/library are not bumped.

2024-12-05 15:16 UTC, dartdart26 reviewed
Looks good! I just asked @goshawk-3 to check the `select!` statement as we discussed it, but maybe he got deeper on that.

2024-12-05 15:16 UTC, dartdart26 commented on docs/getting_started/fhevm/coprocessor/contracts.md
> +# Deploy initial contractsL
Typo?

2024-12-05 15:16 UTC, dartdart26 commented on fhevm-engine/coprocessor/src/tfhe_worker.rs
> +                _ = tokio::time::sleep(tokio::time::Duration::from_millis(args.worker_polling_interval_ms)) => {
@goshawk-3 As we discussed, is this actually relevant here or it would only matter for the `info!` statement below? Will it affect polling?

2024-12-05 15:34 UTC, manoranjith commented on docs/getting_started/fhevm/coprocessor/contracts.md
> +# Deploy initial contractsL
Fixed this.

2024-12-05 15:47 UTC, manoranjith commented on fhevm-engine/coprocessor/src/tfhe_worker.rs
> +                _ = tokio::time::sleep(tokio::time::Duration::from_millis(args.worker_polling_interval_ms)) => {
As i understood, in its current form the `listener.try_recv` is non blocking. If it does no data is available, it returns immediately.

2024-12-05 16:09 UTC, dartdart26 approved these changes

2024-12-05 16:13 UTC, merged